#!/bin/sh

make_credentials () {
  if [ -z $AWS_ACCESS_KEY_ID ]; then
    echo "AWS Access Key ID is not set in the environment variables. AWS credentials will not be created."
  elif [ -z $AWS_SECRET_ACCESS_KEY ]; then
    echo "AWS Secret Access Key is not set in the environment variables.  AWS credentials will not be created."
  else
    echo "Creating AWS credentials file."
    mkdir ~/.aws
    echo "[default]" >> ~/.aws/credentials
    echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
    echo "aws_secret_accesS_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
  fi
}

export VC_007="https://download.vividcortex.com/linux/x86_64/current/vc-agent-007"
export VC_HOME=/vc
export VC_PID_DIR=$VC_HOME
export VC_RUN_DIR=$VC_HOME
export VC_LOG_DIR=$VC_HOME/logs
export VC_LOCK_DIR=$VC_HOME/lock
export VC_AGENT_INSTALL_DIR=$VC_HOME/bin
export VC_DRV_MANUAL_HOST_URI="$DATABASE_URL"
export VC_HOSTNAME="${VC_HOSTNAME:-$(hostname)}"

[ -f ~/.aws/credentials ] || make_credentials

export PATH=$PATH:$VC_AGENT_INSTALL_DIR

exec ${VC_AGENT_INSTALL_DIR}/vc-agent-007 --foreground --forbid-restarts --log-type stderr
